#!/bin/bash

# Server start script tailored for personal use, don't expect explanation.

echo starting ks >> ~/.kliplog
date >> ~/.kliplog
cd /home/klipspringer/klipspringer
#node ks.js /mnt/klipspringer 8080 'alsa:device=hw=1,0' >> ~/.kliplog 2>&1 &
/usr/local/bin/java -cp /home/klipspringer/klipspringer:/home/klipspringer/jars/jflac.jar net.avadeaux.klipspringer.TrackPlayer 'default' 1024 0.2 /home/klipspringer/klipspringer/click.flac
#/usr/local/bin/node main.js /media/klipspringer/porsche 8080 'alsa:device=hw=0,1' 'PCH [plughw:0,1]' /home/klipspringer/klipspringer:/home/klipspringer/jars/jflac.jar >> ~/.kliplog 2>&1 &
/usr/local/bin/node main.js /media/klipspringer/porsche 8080 'alsa:device=hw=0,1' 'default' /home/klipspringer/klipspringer:/home/klipspringer/jars/jflac.jar >> ~/.kliplog 2>&1 &
