#!/usr/bin/python3
#
# xcaffeine: keeps xscreenserver from blanking screen while in fullscreen mode
# Jesper Larsson, 2020-07-20

from time import sleep
from ewmh import EWMH
from subprocess import call

ewmh = EWMH()
while True:
    win = ewmh.getActiveWindow()
    state = ewmh.getWmState(win, str=True)
    if '_NET_WM_STATE_FULLSCREEN' in state:
        call(['xscreensaver-command', '-deactivate'])
    sleep(30)
