* rip cd

cd /home/jesper/klipspringer/ripped/cd
abcde

ls /home/jesper/klipspringer/ripped/cd | grep -v '^audio' | sudo mv `cat` /mnt/klipspringer/cd/

[Desktop Entry]
Version=1.0
Type=Application
Terminal=true
Icon=gnome-panel-launcher
Name=ripcd
Exec=/home/jesper/bin/ripcd.sh %U
Comment=cd rip script
X-Desktop-File-Install-Version=0.22

* rip dvd

cd /home/jesper/klipspringer/ripped/dvd
dvdbackup -M -i /dev/cdrom
eject /dev/cdrom

** Make it play automatically, as root

gcc -o ripdvd ripdvd.c
sudo chown root:root ripdvd
sudo chmod u+s ripdvd
sudo chmod g-w ripdvd
sudo mv ripdvd /usr/local/sbin/

Make file ~/.local/share/applications/ripdvd.desktop:

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon=gnome-panel-launcher
Name=ripdvd
Exec=/usr/local/sbin/ripdvd %U
Comment=dvd rip pseudo-script
X-Desktop-File-Install-Version=0.22


* Information about dvd:

lsdvd /media/klipspringer/porsche/dvd/Last\ Days\ Of\ Disco

* Play movie

mplayer dvd://2 -dvd-device /home/jesper/klipspringer/ripped/dvd/Last\ Days\ Of\ Disco

** Fullscreen on "other screen":

-xineramascreen 1 -fs

** Subtitles:

Force off: -nosub
Choose: -sid <ID> (also see -slang, -vobsubid)

** Deinterlacing
-vf kerndeint

* Power button

1.- sudo gedit /etc/acpi/events/powerbtn

2.- Add # to comment line: #action=/etc/acpi/powerbtn.sh

3.- Add a new line: action=/sbin/poweroff

4.- Save file

5.- Open a console and type: sudo acpid restart

* NFS

** Server

sudo apt-get install nfs-kernel-server

In /etc/exports:
/media/klipspringer/porsche *(rw,sync,no_root_squash)
sudo service nfs-kernel-server start

** Client

sudo apt-get install nfs-common
sudo mkdir /mnt/klipspringer
sudo mount klipspringer.local:/media/klipspringer/porsche /mnt/klipspringer

Runnint mount, this means it's down:

mount.nfs: Failed to resolve server klipspringer.local: Name or service not known

up:

mount.nfs: /mnt/klipspringer is busy or already mounted

mounting (?), or maybe it's stuck, needs umount+mount:

mount.nfs: access denied by server while mounting (null)


/etc/fstab:
192.168.1.5:/media/klipspringer/porsche /mnt/klipspringer nfs ro


* pulse

Pulseaudio is really easy to mess up. Restart it with

pulseaudio -k

Maybe also remove configuration sometimes:

rm -r .config/pulse

On klipspringer, this plays on hdmi (NOTE! -ao must come before file):

mplayer -ao pulse::2 /media/klipspringer/porsche/cd/Per-Oscar_Nilsson_Group_feat._Marcus_Strickland_and_Fredrik_Kronkvist/Now\!/*.flac

... and this plays on DAC:

mplayer -ao pulse::0 /media/klipspringer/porsche/cd/Per-Oscar_Nilsson_Group_feat._Marcus_Strickland_and_Fredrik_Kronkvist/Now\!/*.flac

*Note*: the order of parameters is significant. Placing the -ao last
in the line seems to have no effect.

This matches the output from

pacmd
>>> list-sinks

Strangely, the indexes are 0 and 2. Maybe this changes, should perhaps
parse that file to pick the right one.

** Remote

Put this line in /etc/pulse/default.pa on klipspringer:

load-module module-native-protocol-tcp auth-anonymous=1

That made this possiblen delia :

mplayer -ao pulse:klipspringer.local:0 /mnt/klipspringer/cd/Monica_Zetterlund_\&_Bill_Evans/Waltz_For_Debby/01.Come_Rain_Or_Come_Shine.flac

To add a sink for tunneling on delia, do this in pacmd:

load-module module-tunnel-sink sink_name=kliptun server=tcp:192.168.1.5:4713 


* Wake up Klipspringer

Got info from here
https://help.ubuntu.com/community/WakeOnLan

I set wakeup on in Nuc bios when I created it, and found I just had to
install software now. I installed the etherwake package. The
etherwake command required root access and only worked from a
computer which is itself connected with ethernet. However, the
package also contained the command wakeonlan, which works fine.

* Getting pulseaudio to start properly on halle

To get rid of the error about INET6 address family not supported, I
turned on IPv6 by adding ipv6 to /etc/modules. Look into turning it
on on klipspringer and the router too, maybe that makes pulseaudio
streaming work better?

To get rid of the no DISPLAY problem, I start Xvfb with "Xvfb :99
-screen 0 1x1x8". I have this script, which I set to execute @reboot
in crontab:

#!/bin/bash
Xvfb :99 -screen 0 1x1x8 &
export DISPLAY=:99
pulseaudio --start

Jag kan dock fortfarande inte få autospawn att funka

* Port forwarding

From http://serverfault.com/questions/112795/how-can-i-run-a-server-on-linux-on-port-80-as-a-normal-user

you can redirect connections on port 80 to some other port you can open as normal user.

Run as root:

# iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
As loopback devices (like localhost) do not use the prerouting rules, if you need to use localhost, etc., add this rule as well (thanks @Francesco):

# iptables -t nat -I OUTPUT -p tcp -d 127.0.0.1 --dport 80 -j REDIRECT --to-ports 8080
NOTE: The above solution is not well suited for multi-user systems, as any user can open port 8080 (or any other high port you decide to use), thus intercepting the traffic. (Credits to CesarB).

EDIT: as per comment question - to delete the above rule:

# iptables -t nat --line-numbers -n -L
This will output something like:

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0           tcp dpt:8080 redir ports 8088
2    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0           tcp dpt:80 redir ports 8080
The rule you are interested in is nr. 2, so to delete it:

# iptables -t nat -D PREROUTING 2

** Make it stick

sudo su -c 'iptables-save > /etc/iptables.up.rules'

Put in /etc/network/if-pre-up.d/iptables:

#!/bin/sh
/sbin/iptables-restore < /etc/iptables.up.rules

(and make executable)
